### ISSUE TITLE
update to use shinyjs to remove the tooltip right before the DT proxy replaces the data

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/shiny_crud#11]
Put a good comment above this line about why we do this

**Comment by phoward38** [comment]
Completed w/ bf45693bf471e4a0e9829a86f49392da988aa832

Also, removed `is_deleted` column from `traditional` app (f9b5fec01b5a558603c825dc1ae0288ebdd15c7d) & updated the directory paths in the `data_prep` scripts (6fbc7249974e5ca835ebf799fadda2f022506aca).

@merlinoa Need you to redeploy the `traditional` app when you can

**Comment by merlinoa** [comment]
redeployed thanks!
