### ISSUE TITLE
Add SaveState

### ISSUE THREAD

**Issue by phoward38** [Tychobra/shiny_crud#12]
- [ ] Set `stateSave=TRUE` in DT options
  - Creates inputs in format: `input$<table_id>_<state_metric>` (`<table_id` is NOT namespaced)
  - Ex: `input$apps_table_rows_current`
- [ ] Add `resetPaging` work-around for deleting the 11th, 21st, etc. row (assuming pageLength of 10) from `polished_hosted`

Reference (after `replaceData`):
```
      pre_rows_current <- input$apps_table_rows_current

      if (length(pre_rows_current) == 1 && nrow(out) < nrow(apps_table_prep())) {

        pre_rows_all <- input$apps_table_rows_all

        select_page <- (which(pre_rows_current == pre_rows_all) - 1) / 10

        apps_table_proxy %>% selectPage(page = select_page) %>% replaceData(out, resetPaging = FALSE, rownames = FALSE)

      } else {

        apps_table_proxy %>% replaceData(out, resetPaging = FALSE, rownames = FALSE)
      }
```
- **NOTE:** State remained saved on local system. Try clearing sessionState

**Comment by merlinoa** [comment]
This didn't end up working well / introduced more complexity than it was worth.  No longer implementing.
