### ISSUE TITLE
Change from callModule() to moduleServer()

### ISSUE THREAD

**Issue by yyyguy** [Tychobra/shiny_crud#13]
From https://shiny.rstudio.com/articles/modules.html

Note: Prior to Shiny 1.5.0, we recommended using callModule() to invoke modules. From 1.5.0 onward, we recommend using moduleServer() instead, because it has simpler syntax for using the module. Additionally, new-style modules can be tested with the testServer() function, also introduced in Shiny 1.5.0. If you would like to see how to migrate from old to new-style modules and see how they compare, see the Migrating from callModule to moduleServer section, below.
I have been making modifications to support CRUD functionality for a project I am working on.

BTW, the shiny_crud app is a nice starter functionality.

**Comment by merlinoa** [comment]
Thanks @yyyguy !  Glad this repo could serve as nice starter functionality for you!  That was the idea behind making the repo and posts.

Yes, I agree that updating to the new Shiny module syntax would be a nice upgrade to this repo.  Please feel free to submit a PR.

**Comment by merlinoa** [comment]
After testing out the new module syntax I actually prefer the old syntax.  I might change my mind once I try out more of the new Shiny test functions. Going to close out for now.
