### ISSUE TITLE
Table filter cannot be enabled

### ISSUE THREAD

**Issue by Patrickhamachado** [Tychobra/shiny_crud#16]
Hello. Thanks because of your work.

It is really strange, but when filter is enabled (filter = "top") in the datatable function (file: .\01_traditional\shiny_app\R\cars_table_module.R, rungs 141 to 174), the data creation and data update stop working: the Submit button doesn't do anything. 

Patrick

**Comment by phoward38** [comment]
@Patrickhamachado Thanks for pointing this out. The console throws an error when the modal opens: `Uncaught Error: Unable to find "selectize-plugin-a11y" plugin`.

So, this issue involves conflicts between `selectize.js` (from `selectInput`) & `datatables`. If you change the argument in both `selectInput`s to `selectize = FALSE`, the modal works correctly again.

**Comment by Patrickhamachado** [comment]
Thanks a lot Patrick!
