### ISSUE TITLE
file locking question

### ISSUE THREAD

**Issue by RichardHooijmaijers** [Tychobra/shiny_crud#8]
Was wondering if you have any thoughts about file locking. I experienced some issues in the past when multiple people try to adapt the underlying database at the same time...

**Comment by merlinoa** [comment]
The SQLite database should take care of that automatically I believe.  If you know of circumstances where SQLite will have file locking issues I would be very interested to hear more about it.

**Comment by RichardHooijmaijers** [comment]
Sorry, realized I was maybe a bit vague. 
SQLite does file locking automatically: [link](https://sqlite.org/lockingv3.html#locking)
This means that when an entry is added, the database is briefly locked. When it is locked, a second user will get an error when trying to add to that database (e.g. could not execute1: database is locked). For smaller databases/few users this is not really an issue, however if size increases it could be an issue. For this reason I used the [filelock package](https://cran.r-project.org/web/packages/filelock/index.html) in which you can specify a timeout. If there are better/more elegant ways to handle this I am interested!

**Comment by merlinoa** [comment]
Cool thanks for the info and links!  This demo is only meant for a few users and it will probably only run in 1 R process, so we shouldn't run into any file locking issues.  Definitely something to consider when scaling up though.  Thanks!

**Comment by cherif40** [comment]
Very interesting work, thank you.
Is it possible to add a new function allowing the user of the shiny application to add a new variable from the application interface?
