### ISSUE TITLE
 Add a new variable 

### ISSUE THREAD

**Issue by cherif40** [Tychobra/shiny_crud#9]
Very interesting work, thank you.
Is it possible to add a new function allowing the user of the shiny application to add a new variable from the application interface?

**Comment by merlinoa** [comment]
Thanks @cherif40

Yes that is certainly possible.  You could add a new column to the table in SQL with something like

```
ALTER TABLE table_name
  ADD new_column_name column_definition;
```

You can execute the SQL in a `DBI::dbExecute()`.  You will then need to build out the UI.  The exact implementation of course depends on the functionality you are trying to achieve.

**Comment by cherif40** [comment]
Thanks @merlinoa, it's better now.
Another question please if I don't disturb you, when I ran the application, I encountered two problems.
1 / DBI :: dbWriteTable (
+ conn,
+ name = "mtcars",
+ value = dat,
+ overwrite = FALSE,
+ append = TRUE
+)
Error: Columns `is_deleted` not found

2 / Listening on http://127.0.0.1:4915
Warning: Error in session $ makeScope: attempt to apply non-function
   56: callModule

**Comment by merlinoa** [comment]
@cherif40 It looks like you might be using the "transactional" data for the "traditional".  I went ahead and just added the sqlite db to GitHub, so you now shouldn't need to do any data prep.  If you pull now, you should be able to run the "traditional" app locally.

**Comment by cherif40** [comment]
@merlinoa I have this error message after runing the "traditional" app locally:
Warning: Error in cars_table_module_ui: could not find function "cars_table_module_ui"
  55: dots_list
  54: div
  49: fluidPage

**Comment by merlinoa** [comment]
I think you need to install the development version of shiny from GitHUb using: `remotes::install_github("rstudio/shiny")`.  The new version of shiny automatically loads all "*.R" files in the "R/" directory right before the app starts up.

I am going to close out this issue.  Please feel free to open a new issue if you have a specific issue with this app.

**Comment by cherif40** [comment]
Ok, thank you very much, it's very useful for me, however to fix problem when using: remotes::install_github("rstudio/shiny"), I solve this with the following code:

renv::init()
remotes::install_github("rstudio/shiny")
renv::snapshot()
renv::install("rstudio/shiny")
